// Generated by CoffeeScript 1.10.0

/*
  Front-end handlebars parser
  @author: K.Perov <fe3dback@yandex.ru>
 */

(function() {
  var MoreDraw;

  MoreDraw = (function() {
    var dataCache, partials;

    partials = null;

    dataCache = null;

    function MoreDraw() {
      if ((typeof __handlebars_server_partials !== "undefined" && __handlebars_server_partials !== null)) {
        this.partials = __handlebars_server_partials;
      }
      if ((typeof __handlebars_server_data !== "undefined" && __handlebars_server_data !== null)) {
        this.dataCache = __handlebars_server_data;
      }
    }

    MoreDraw.prototype.render = function(name, data) {
      var $el, tpl;
      name = name.replace('/', "__");
      $el = $("#hb-" + name);
      if ($el == null) {
        return "";
      }
      tpl = Handlebars.compile($el.html());
      return tpl(data, {
        'partials': this.partials
      });
    };

    MoreDraw.prototype.getData = function(name, index) {
      var data, ref;
      if (this.dataCache == null) {
        return;
      }
      data = (ref = this.dataCache[name]) != null ? ref[index] : void 0;
      if (data == null) {
        return;
      }
      return data;
    };

    return MoreDraw;

  })();

  window.MoreDraw = new MoreDraw();

}).call(this);
